// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHXRj6q05sFUJcYxgIdKRguzjOjoiVVHM',
    appId: '1:631326908525:web:5dc3bdbac5fb265665df64',
    messagingSenderId: '631326908525',
    projectId: 'collservice',
    authDomain: 'collservice.firebaseapp.com',
    storageBucket: 'collservice.firebasestorage.app',
    measurementId: 'G-4KJB2F3JHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWMFq0QeJX1f8R8NLiWLTx0Trds_5r3q8',
    appId: '1:631326908525:android:ec787f4b96a61f6d65df64',
    messagingSenderId: '631326908525',
    projectId: 'collservice',
    storageBucket: 'collservice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8i-mFMQs9hlRZoTulJOKmtFurl17n3wk',
    appId: '1:631326908525:ios:258b575ea97d822065df64',
    messagingSenderId: '631326908525',
    projectId: 'collservice',
    storageBucket: 'collservice.firebasestorage.app',
    iosBundleId: 'com.example.coolservice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8i-mFMQs9hlRZoTulJOKmtFurl17n3wk',
    appId: '1:631326908525:ios:258b575ea97d822065df64',
    messagingSenderId: '631326908525',
    projectId: 'collservice',
    storageBucket: 'collservice.firebasestorage.app',
    iosBundleId: 'com.example.coolservice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHXRj6q05sFUJcYxgIdKRguzjOjoiVVHM',
    appId: '1:631326908525:web:2c75763e7a1070c865df64',
    messagingSenderId: '631326908525',
    projectId: 'collservice',
    authDomain: 'collservice.firebaseapp.com',
    storageBucket: 'collservice.firebasestorage.app',
    measurementId: 'G-0D58TZR0F1',
  );
}
